-- MySQL Script generated by MySQL Workbench
-- Mon Mar 17 15:21:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aire_libre_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aire_libre_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aire_libre_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aire_libre_db` ;

-- -----------------------------------------------------
-- Table `aire_libre_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL DEFAULT 'visitante/administrador',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(45) NOT NULL DEFAULT 'visita_default',
  `image` VARCHAR(150) NOT NULL,
  `id_roles` INT NOT NULL,
  PRIMARY KEY (`id`, `id_roles`),
  INDEX `fk_users_roles1_idx` (`id_roles` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`id_roles`)
    REFERENCES `aire_libre_db`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`addresses` (
  `id` INT NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `number` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_addresses_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aire_libre_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`brands` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`invoices` (
  `id` INT NOT NULL,
  `total` INT NOT NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id`, `id_users`),
  INDEX `fk_invoices_users1_idx` (`id_users` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_users1`
    FOREIGN KEY (`id_users`)
    REFERENCES `aire_libre_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `image` VARCHAR(150) NOT NULL,
  `id_brand` INT NOT NULL,
  `brand` VARCHAR(100) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id`, `id_brand`, `id_category`),
  INDEX `fk_product_brand1_idx` (`id_brand` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`id_brand`)
    REFERENCES `aire_libre_db`.`brands` (`id`),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`id_category`)
    REFERENCES `aire_libre_db`.`categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aire_libre_db`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aire_libre_db`.`items` (
  `id` INT NOT NULL,
  `id_invoices` INT NOT NULL,
  `products_id` INT UNSIGNED NOT NULL,
  ` quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_items_invoices1_idx` (`id_invoices` ASC) VISIBLE,
  INDEX `fk_items_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_invoices1`
    FOREIGN KEY (`id_invoices`)
    REFERENCES `aire_libre_db`.`invoices` (`id`),
  CONSTRAINT `fk_items_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `aire_libre_db`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
